"""
PDB id -> (GPCR family, protein) for the 133 case-study targets, taken from
Supplementary Table 1 of the manuscript.

Supplementary Table 1 lists five PDB ids under two proteins and omits three targets. They are
resolved here from the ligand and UniProt mapping:

* 6d9h, 7ld4: adenosine A1 (aa1r), not muscarinic M4
* 6u1n: muscarinic M2 (acm2), not V2R
* 7t11: somatostatin SSTR2, not kappa opioid
* 7ul2: neurotensin NTR1, not kappa opioid
* 7v6a (M4), 8dzs (kappa opioid) and 8fx5 (V2R) are absent from the table
"""

PDB_TO_FAMILY = {
    "3odu": ("Chemokine", "cxcr4_human"),
    "3oe8": ("Chemokine", "cxcr4_human"),
    "3pbl": ("Dopamine", "drd3_human"),
    "3rze": ("Histamine", "hrh1_human"),
    "3v2w": ("Lysophospholipid (S1P)", "s1pr1_human"),
    "4ea3": ("Opioid", "oprx_human"),
    "4iaq": ("5-Hydroxytryptamine", "5ht1b_human"),
    "4k5y": ("Corticotropin-releasing factor", "crfr1_human"),
    "4oo9": ("Metabotropic glutamate", "grm5_human"),
    "4qkx": ("Adrenoceptors", "adrb2_human"),
    "4s0v": ("Orexin", "ox2r_human"),
    "4z9g": ("Corticotropin-releasing factor", "crfr1_human"),
    "5cgc": ("Metabotropic glutamate", "grm5_human"),
    "5cxv": ("Acetylcholine (muscarinic)", "acm1_human"),
    "5dhg": ("Opioid", "oprx_human"),
    "5dhh": ("Opioid", "oprx_human"),
    "5k2d": ("Adenosine", "aa2ar_human"),
    "5l7i": ("Frizzled (SMO)", "smo_human"),
    "5nm4": ("Adenosine", "aa2ar_human"),
    "5nx2": ("Glucagon receptor", "glp1r_human"),
    "5o9h": ("Complement peptide", "c5ar1_human"),
    "5tud": ("5-Hydroxytryptamine", "5ht2b_human"),
    "5tzy": ("Free fatty acid", "ffar1_human"),
    "5uen": ("Adenosine", "aa1r_human"),
    "5unf": ("Angiotensin", "agtr2_human"),
    "5unh": ("Angiotensin", "agtr2_human"),
    "5v54": ("5-Hydroxytryptamine", "5ht1b_human"),
    "5wqc": ("Orexin", "ox2r_human"),
    "5yc8": ("Acetylcholine (muscarinic)", "acm2_human"),
    "5ywy": ("Prostanoid", "pe2r4_human"),
    "6ak3": ("Prostanoid", "pe2r3_human"),
    "6bqh": ("5-Hydroxytryptamine", "5ht2c_human"),
    "6d26": ("Prostanoid", "pd2r2_human"),
    "6d27": ("Prostanoid", "pd2r2_human"),
    "6d9h": ("Adenosine", "aa1r_human"),
    "6dry": ("5-Hydroxytryptamine", "5ht2b_human"),
    "6ds0": ("5-Hydroxytryptamine", "5ht2b_human"),
    "6fuf": ("Opsins", "opsd_human"),
    "6kpf": ("Cannabinoid", "cnr2_human"),
    "6kqi": ("Cannabinoid", "cnr1_human"),
    "6m9t": ("Prostanoid", "pe2r3_human"),
    "6me4": ("Melatonin", "mtr1a_human"),
    "6me6": ("Melatonin", "mtr1b_human"),
    "6me8": ("Melatonin", "mtr1b_human"),
    "6n4b": ("Cannabinoid", "cnr1_human"),
    "6ot0": ("Frizzled (SMO)", "smo_human"),
    "6tod": ("Orexin", "ox1r_human"),
    "6tp6": ("Orexin", "ox1r_human"),
    "6tq6": ("Orexin", "ox1r_human"),
    "6u1n": ("Acetylcholine (muscarinic)", "acm2_human"),
    "6up7": ("Neurotensin", "ntr1_human"),
    "6wha": ("5-Hydroxytryptamine", "5ht2a_human"),
    "6xbj": ("Frizzled (SMO)", "smo_human"),
    "6zfz": ("Acetylcholine (muscarinic)", "acm1_human"),
    "6zg4": ("Acetylcholine (muscarinic)", "acm1_human"),
    "7bts": ("Adrenoceptors", "adrb1_human"),
    "7bu6": ("Adrenoceptors", "adrb1_human"),
    "7bvq": ("Adrenoceptors", "adrb1_human"),
    "7c2e": ("Glucagon receptor", "glp1r_human"),
    "7c4s": ("Lysophospholipid (S1P)", "s1pr3_human"),
    "7c61": ("5-Hydroxytryptamine", "5ht1b_human"),
    "7cmv": ("Dopamine", "drd3_human"),
    "7d7m": ("Prostanoid", "pe2r4_human"),
    "7db6": ("Melatonin", "mtr1a_human"),
    "7dfl": ("Histamine", "hrh1_human"),
    "7dfp": ("Dopamine", "drd2_human"),
    "7dhi": ("Adrenoceptors", "adrb2_human"),
    "7eo2": ("Lysophospholipid (S1P)", "s1pr1_human"),
    "7ew2": ("Lysophospholipid (S1P)", "s1pr3_human"),
    "7ew4": ("Lysophospholipid (S1P)", "s1pr3_human"),
    "7f1o": ("Dopamine", "drd1_human"),
    "7f23": ("Dopamine", "drd1_human"),
    "7f9y": ("Ghrelin", "ghsr_human"),
    "7jni": ("Angiotensin", "agtr2_human"),
    "7joz": ("Dopamine", "drd1_human"),
    "7jvr": ("Dopamine", "drd2_human"),
    "7l1v": ("Orexin", "ox2r_human"),
    "7ld4": ("Adenosine", "aa1r_human"),
    "7m8w": ("Prostanoid", "pd2r2_human"),
    "7mta": ("Opsins", "opsd_human"),
    "7mtb": ("Opsins", "opsd_human"),
    "7na8": ("Ghrelin", "ghsr_human"),
    "7s15": ("Glucagon receptor", "glp1r_human"),
    "7sus": ("Apelin", "apj_human"),
    "7t11": ("Somatostatin", "ssr2_human"),
    "7t6s": ("Formylpeptide", "fpr2_human"),
    "7t6u": ("Formylpeptide", "fpr2_human"),
    "7t6v": ("Formylpeptide", "fpr2_human"),
    "7t94": ("Acetylcholine (muscarinic)", "acm2_human"),
    "7ul2": ("Neurotensin", "ntr1_human"),
    "7v3z": ("Cannabinoid", "cnr1_human"),
    "7v68": ("Acetylcholine (muscarinic)", "acm4_human"),
    "7v6a": ("Acetylcholine (muscarinic)", "acm4_human"),
    "7vgy": ("Melatonin", "mtr1a_human"),
    "7vh0": ("Melatonin", "mtr1b_human"),
    "7vig": ("Lysophospholipid (S1P)", "s1pr1_human"),
    "7w0l": ("Apelin", "apj_human"),
    "7w0m": ("Apelin", "apj_human"),
    "7w2z": ("Ghrelin", "ghsr_human"),
    "7wc8": ("5-Hydroxytryptamine", "5ht2a_human"),
    "7xav": ("Somatostatin", "ssr2_human"),
    "7xt8": ("5-Hydroxytryptamine", "5ht4r_human"),
    "7xt9": ("5-Hydroxytryptamine", "5ht4r_human"),
    "7xta": ("5-Hydroxytryptamine", "5ht4r_human"),
    "7y26": ("Somatostatin", "ssr2_human"),
    "7y66": ("Complement peptide", "c5ar1_human"),
    "7y67": ("Complement peptide", "c5ar1_human"),
    "7yit": ("Opioid", "oprk_human"),
    "7yu3": ("Lysophospholipid (LPA)", "lpar1_human"),
    "7yu4": ("Lysophospholipid (LPA)", "lpar1_human"),
    "7yu7": ("Lysophospholipid (LPA)", "lpar1_human"),
    "8a2o": ("Adenosine", "aa2ar_human"),
    "8dpg": ("5-Hydroxytryptamine", "5ht2c_human"),
    "8dph": ("5-Hydroxytryptamine", "5ht2c_human"),
    "8dzs": ("Opioid", "oprk_human"),
    "8eit": ("Free fatty acid", "ffar1_human"),
    "8ejc": ("Free fatty acid", "ffar1_human"),
    "8fx5": ("Vasopressin and oxytocin", "v2r_human"),
    "8gd9": ("Prostanoid", "pe2r4_human"),
    "8gdc": ("Prostanoid", "pe2r3_human"),
    "8ge3": ("Adrenoceptors", "adrb2_human"),
    "8gtm": ("Corticotropin-releasing factor", "crfr1_human"),
    "8guq": ("Cannabinoid", "cnr2_human"),
    "8gut": ("Cannabinoid", "cnr2_human"),
    "8irs": ("Dopamine", "drd2_human"),
    "8irt": ("Dopamine", "drd3_human"),
    "8jpf": ("Neurotensin", "ntr1_human"),
    "8jt8": ("5-Hydroxytryptamine", "5ht2a_human"),
    "8t6j": ("Metabotropic glutamate", "grm5_human"),
    "8u4p": ("Chemokine", "cxcr4_human"),
    "8wrz": ("Vasopressin and oxytocin", "v2r_human"),
    "8wu1": ("Vasopressin and oxytocin", "v2r_human"),
    "8yn2": ("Histamine", "hrh1_human"),
}
