"""
KarmaDock constants
"""

KARMADOCK_FILE_NAME = "top_karmadock_results.csv"

"""
Columns
"""
KARMADOCK_RUN = "run"
KARMADOCK_RMSD = "RMSD"
KARMADOCK_FF_RMSD = "FF_RMSD"
KARMADOCK_ALIGNED_RMSD = "Aligned_RMSD"
KARMADOCK_RAW_SCORE = "score"
KARMADOCK_PDB_ID = "pdb_id"
KARMADOCK_PROTEIN = "protein"
KARMADOCK_LIGAND = "ligand"
KARMADOCK_COLUMNS_TO_DROP = [
    KARMADOCK_RMSD,
    KARMADOCK_FF_RMSD,
    KARMADOCK_ALIGNED_RMSD,
    KARMADOCK_RUN,
    KARMADOCK_PROTEIN,
    KARMADOCK_LIGAND,
]
KARMADOCK_COLUMNS = [
    KARMADOCK_RAW_SCORE,
    KARMADOCK_PDB_ID,
    KARMADOCK_RMSD,
    KARMADOCK_FF_RMSD,
    KARMADOCK_ALIGNED_RMSD,
    KARMADOCK_RUN,
    KARMADOCK_PROTEIN,
    KARMADOCK_LIGAND,
]

"""
Folders
"""
KARMADOCK_GRAPHS_FOLDER = "graphs"
KARMADOCK_RESULTS_FOLDER = "results"
KARMADOCK_DATA_FOLDER = "data"
